
#version: '3.8'
services:
  edge_ai_ros2:
    build:
      context: .
      #dockerfile: Dockerfile.jetson
      dockerfile: Dockerfile
    container_name: jetson_pipeline_dev
    privileged: true
    pid: "host"
    
    volumes:
      - ~/ros2_erdem_ws:/ros2_erdem_ws
      - ./:/workspace
      # --- Aşağıdaki donanım bağlamaları Jetson'a özel olduğu için lokalde kapatıldı
 #     - /dev:/dev
 #     - /sys:/sys
  #    - /proc:/proc
   #   - /usr/bin/tegrastats:/usr/bin/tegrastats
    #  - /usr/sbin/nvpmodel:/usr/sbin/nvpmodel
     # - /usr/bin/nvpmodel:/usr/bin/nvpmodel
    #  - /etc/nvpmodel.conf:/etc/nvpmodel.conf
     # - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
     # - /var/lib/nvpmodel:/var/lib/nvpmodel
     # - /sys/kernel/debug:/sys/kernel/debug
      - /var/run:/var/run
   # environment:
      # Konteynerin bu kütüphaneleri nerede bulacağını söylüyoruz
   #   - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra:${LD_LIBRARY_PATH}
    network_mode: "host"
    ipc: host
    
#    devices:
    #  - /dev/video0:/dev/video0 
    #  - /dev/video1:/dev/video1 
    #  - /dev/video2:/dev/video2 
    #  - /dev/video3:/dev/video3 
    #  - /dev/video4:/dev/video4 
    #  - /dev/video5:/dev/video5 
     # - /dev/video6:/dev/video6 
    #  - /dev/video7:/dev/video7 
    #  - /dev/bus/usb:/dev/bus/usb
    
    tty: true
    stdin_open: true

