FROM nvcr.io/nvidia/l4t-ml:r36.2.0-py3

RUN apt-get update && apt-get install -y curl gnupg2

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=arm64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main" > /etc/apt/sources.list.d/ros2.list


RUN apt-get update && apt-get install -y \
    ros-humble-ros-base \
    python3-colcon-common-extensions \
    python3-pip \
    v4l-utils \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install setuptools==65.5.0 numpy
RUN /bin/bash -c "cd /tmp && git clone https://github.com/ros/diagnostics.git -b ros2 \
    && cd diagnostics \
    && source /opt/ros/humble/setup.bash \
    && colcon build --packages-select diagnostic_updater \
    && colcon build --packages-select diagnostic_common_diagnostics \
    && echo 'source /tmp/diagnostics/install/setup.bash' >> /root/.bashrc"

    # RealSense SDK kurulumu
RUN apt-get update && apt-get install -y libusb-1.0-0-dev libudev-dev pkg-config libssl-dev
RUN git clone https://github.com/IntelRealSense/librealsense.git /tmp/librealsense \
    && cd /tmp/librealsense \
    && mkdir build && cd build \
    && cmake .. -DFORCE_RSUSB_BACKEND=ON -DBUILD_WITH_CUDA=ON -DCMAKE_BUILD_TYPE=release -DBUILD_EXAMPLES=OFF -DBUILD_GRAPHICAL_EXAMPLES=OFF \
    && make -j$(nproc) \
    && make install \
    && ldconfig

RUN cd /tmp && apt-get update && \
    apt-get download ros-humble-cv-bridge && \
    dpkg --force-depends -i ros-humble-cv-bridge*.deb && \
    ldconfig && \
    rm -f ros-humble-cv-bridge*.deb

# Eksik Python paketleri
RUN pip3 install matplotlib psutil

RUN printf '#!/bin/bash\nexec "$@"\n' > /usr/local/bin/sudo && \
    chmod +x /usr/local/bin/sudo
RUN /bin/bash -c "cd /tmp && git clone https://github.com/ros-perception/image_common.git -b humble \
    && cd image_common \
    && source /opt/ros/humble/setup.bash \
    && source /tmp/diagnostics/install/setup.bash \
    && colcon build --packages-select image_transport \
    && echo 'source /tmp/image_common/install/setup.bash' >> /root/.bashrc"
WORKDIR /workspace

RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
RUN echo "if [ -f /workspace/install/setup.bash ]; then source /workspace/install/setup.bash; fi" >> ~/.bashrc
RUN echo "source /tmp/diagnostics/install/setup.bash" >> /root/.bashrc
CMD ["bash"]
